apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: ${INFLUX_URL}
    isDefault: true
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: rate_limiter
    secureJsonData:
      token: ${INFLUX_TOKEN}